import { useState } from 'react';
import { parseSourceCode } from '../../utils/astParser';
import type { ParsedCodeFile } from '../../types/ast';
import { PlusCircle, X, Sparkles } from 'lucide-react';

interface IngestModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAddFile: (file: ParsedCodeFile) => void;
}

export function IngestModal({ isOpen, onClose, onAddFile }: IngestModalProps) {
  const [filePath, setFilePath] = useState('components/CartDrawer.tsx');
  const [rawCode, setRawCode] = useState(`import React, { useState } from 'react';

export function CartDrawer({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [promoCode, setPromoCode] = useState('');
  const [discount, setDiscount] = useState(0);

  async function applyCoupon() {
    const res = await fetch('/api/coupon', {
      method: 'POST',
      body: JSON.stringify({ promoCode })
    });
    const data = await res.json();
    if (data.valid) setDiscount(data.amount);
  }

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex justify-end">
      <div className="w-80 bg-zinc-900 p-4">
        <button onClick={onClose}>Close</button>
        <input value={promoCode} onChange={(e) => setPromoCode(e.target.value)} />
        <button onClick={applyCoupon}>Apply</button>
      </div>
    </div>
  );
}`);

  if (!isOpen) return null;

  const handleIngest = () => {
    if (!rawCode.trim()) return;
    const parsed = parseSourceCode(filePath, rawCode);
    onAddFile(parsed);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#08090a] border border-[#23252a] rounded-xl max-w-2xl w-full p-6 relative shadow-2xl flex flex-col max-h-[90vh]">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-[#8a8f98] hover:text-white"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center gap-2 mb-2 text-[#5e6ad2]">
          <PlusCircle className="w-5 h-5" />
          <h3 className="text-base font-semibold text-[#f7f8f8]">
            Ingest Vibe Code File
          </h3>
        </div>
        <p className="text-xs text-[#8a8f98] mb-4">
          Paste any React/TypeScript component, hook, or API route generated by Cursor, v0, or Claude Code to map its architecture.
        </p>

        <div className="space-y-3 flex-1 overflow-hidden flex flex-col">
          <div>
            <label className="text-xs font-mono text-[#8a8f98] block mb-1">
              File Virtual Path
            </label>
            <input
              type="text"
              value={filePath}
              onChange={(e) => setFilePath(e.target.value)}
              placeholder="e.g. components/Header.tsx"
              className="w-full bg-[#121316] border border-[#23252a] rounded-lg px-3 py-1.5 text-xs text-[#f7f8f8] outline-none font-mono focus:border-[#5e6ad2]"
            />
          </div>

          <div className="flex-1 flex flex-col min-h-[220px]">
            <label className="text-xs font-mono text-[#8a8f98] block mb-1">
              Component / Source Code
            </label>
            <textarea
              value={rawCode}
              onChange={(e) => setRawCode(e.target.value)}
              placeholder="Paste code here..."
              className="flex-1 w-full bg-[#121316] border border-[#23252a] rounded-lg p-3 text-xs text-[#f7f8f8] font-mono resize-none outline-none focus:border-[#5e6ad2]"
            />
          </div>
        </div>

        <div className="flex items-center justify-between pt-4 mt-4 border-t border-[#23252a]">
          <span className="text-[11px] font-mono text-[#62666d]">
            Parsed 100% in browser via AST extraction
          </span>
          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-xs text-[#8a8f98] hover:text-white rounded-lg hover:bg-[#121316]"
            >
              Cancel
            </button>
            <button
              onClick={handleIngest}
              className="px-4 py-2 bg-[#5e6ad2] hover:bg-[#828fff] text-white text-xs font-medium rounded-lg flex items-center gap-1.5 transition-colors"
            >
              <Sparkles className="w-3.5 h-3.5" />
              Visualize Architecture
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
